name: Python - Master Push

# run (and build) only py3.10 but on all platforms
# pull_request.yml tests all py versions but only on ubuntu

on:
  push:
    branches:
      - 'nn-python-packaging'
    paths-ignore:
      - "*.md"
      - .circleci/
      - docs/
      - run_route_scripts/
      - test_requests/

# env:
#   VCPKG_VERSION: '8040303'
#   VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions
#   VCPKG_DISABLE_COMPILER_TRACKING: ON

jobs:
  build_wheels:
    name: Push - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: ubuntu-latest
            platform: linux
          # - image: windows-latest
          #   platform: windows
          # - image: macos-latest
          #   platform: macos

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: /root/.ccache
        key: ccache-manylinux_2_28_x86_64-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        restore-keys: ccache-manylinux_2_28_x86_64-

    # only build the earliest supported python version
    - uses: pypa/cibuildwheel@v2.23.3

    - name: Save cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /root/.ccache
        key: ccache-manylinux_2_28_x86_64-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl

  upload_all:
    name: Upload if release
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: https://test.pypi.org/legacy/
        user: nilsnolde
        password: ${{ secrets.PYPI_PWD }}
