name: Python - Master Push

# run (and build) only py3.10 but on all platforms
# pull_request.yml tests all py versions but only on ubuntu

on:
  push:
    # branches-ignore:
    # # TODO: change this to `master`
    #   - '*'
    branches:
      - 'nn-python-packaging'
    paths-ignore:
      - "*.md"
      - .circleci/
      - docs/
      - run_route_scripts/
      - test_requests/

jobs:
  build_wheels:
    name: Push - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: ubuntu-latest
            platform: linux
          # - image: windows-latest
          #   platform: windows
          # - image: macos-latest
          #   platform: macos
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        # we need to fetch all tags for setuptools-scm to work properly
        fetch-depth: 0
        fetch-tags: true

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Get branch name
      run: echo "VALHALLA_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

    - name: Determine package to publish, pyvalhalla(-git)
      run: |
        VALHALLA_RELEASE_PKG="pyvalhalla"
        if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
          VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
        fi
        echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: /project/.cache/ccache
        key: ccache-manylinux_2_28_x86_64-${{ env.VALHALLA_BRANCH }}
        restore-keys: ccache-manylinux_2_28_x86_64-

    # only build the earliest supported python version
    - uses: pypa/cibuildwheel@v2.23.3
      env:
        # /host is mounted from the host system to the manylinux container
        CIBW_ENVIRONMENT: >
          CCACHE_DIR=/host/project/.cache/ccache
          VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}

    - name: Save cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /project/.cache/ccache
        key: ccache-manylinux_2_28_x86_64-${{ env.VALHALLA_BRANCH }}

    - name: Print wheelhouse
      run: |
        ls -l wheelhouse

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl

  upload_all:
    name: Upload if release
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build_wheels]
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT from Github for PyPI

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
